apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astrix-app
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/roncohen4/astrix.git'
    path: '.'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
