apiVersion: apps/v1
kind: Deployment
metadata:
  name: astrix-app
spec:
  selector:
    matchLabels:
      app: astrix-app
  template:
    metadata:
      labels:
        app: astrix-app
      annotations:
        configmap.reloader.stakater.com/reload: "astrix-app"
    spec:
      containers:
      - name: astrix-app
        image: roncohen159753/astrix-app:1.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80