apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/stakater/Reloader.git'
    targetRevision: HEAD
    path: 'deployments/kubernetes/chart/reloader'
    helm:
      values: |
        replicaCount: 1
        image:
          repository: stakater/reloader
          tag: latest
        service:
          type: ClusterIP
          port: 8080
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
